### ISSUE TITLE
Change `help` in npm script

### ISSUE THREAD

**Issue by farskid** [jxnblk/mdx-deck#163]
One of the NPM scripts defined in package.json is names `help`, so that when you run it, you could see the list of options for mdx-deck CLI.

It works perfectly with npm since we use `npm run help` but using it with `Yarn`, people tend to use `yarn help` and it brings up the Yarn's help manual. probably changing it to something else might help?

**Comment by jxnblk** [comment]
Why does `yarn help` do `npm run help`??

**Comment by connor-baer** [comment]
`yarn` allows you to omit the `run` part, so e.g. instead of `yarn run build` you can do `yarn build`. However, some keywords are reserved and one of these is `help`. So `yarn help` brings up `yarn`'s _own_ manual instead of running the `help` script.

An easy workaround is to use `yarn run help`, this will run the `help` scrip as expected and display the `mdx-deck` manual.

**Comment by jxnblk** [comment]
Ah, I think I misunderstood. So `yarn help` still pulls up Yarn's help and `yarn run help` with run the npm run script? If that's the case, I don't think anything needs to change in this repo

**Comment by farskid** [comment]
@jxnblk True. I'll close then.
