### ISSUE TITLE
Using CodeSandbox (Containers) to make it possible to live collaborate on decks

### ISSUE THREAD

**Issue by JReinhold** [jxnblk/mdx-deck#185]
Hi!

I think mdx-deck is super great! 🤗 When reading [the announcement of CodeSandbox Containers](https://hackernoon.com/codesandbox-containers-5864a8f26715), I thought that it would be ideal to be able to run mdx-deck in a CodeSandbox, so multiple people could edit the deck live with each other. If possible, I would suggest that we link to an mdx-deck CodeSandbox template, that people can start work from. 

(CodeSandbox Containers makes it possible to run any nodejs scripts in CodeSandbox, not just predertimed templates)

I tried giving it a go here:
[![Edit mdx-deck PoC](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1j277qw8j)

But as you can see, it doesn't quite work (at least as of 30/09/18, all it shows is an nginx error). I tried to use `mdx-deck --port 8000 --no-open deck.mdx` to mimic the behavior of other templates that use port 8000 like Gatsby, but it didn't work.

If you think this has value to the community, I'll continue my endeavor in trying to make it work, I just wanted to hear your initial thoughts and comments first. 🙂

PS: This also has the added benefit of giving newcomers an easy entry into mdx-deck, as they don't have to install anything at all, they just have to fork the official mdx-deck sandbox.

**Comment by jxnblk** [comment]
Yeah, it should be possible for mdx-deck to work on CodeSandbox now. I have a sandbox running mdx-go (which is a similar setup) here: https://codesandbox.io/s/6jm07qw1yk

I had to go to the server control panel on the left (icon looks like three corns on the cob) and click *Restart Sandbox* to get it to work, if that's any help. Also started with the Next.js template as a base

**Comment by JReinhold** [comment]
Arh, maybe using the Next.js is the missing link, I'll give it a try. 🙂

**Comment by lbogdan** [comment]
Hey guys, Bogdan from CodeSandbox here!

Unfortunately **2.** would be quite hard to implement - even if we'd manage to proxy the websocket port, too (which is on the list of upcoming features, but it has a pretty low priority right now - so proxy the main port to `https://sandbox-id.sse.codesandbox.io` and all subsequent opened ports to something like `https://port.sandbox-id.sse.codesandbox.io`), you would still have to be aware you're running in CodeSandbox and use the correct URL (instead of `ws://localhost:port`).

Another suggestion would be to:
4. Multiplex the websocket on the same port you're serving the deck - the same as, for example, webpack does with its HMR (hot module replacement) websocket.

**Comment by jxnblk** [comment]
I suspect the mdx-deck dev server could be updated to work more similarly to mdx-go (using connect and webpack middleware instead of koa), which I think would get around the issues you're seeing

**Comment by SaraVieira** [comment]
@jxnblk Is this planned for version 2 ? It would be amazing

**Comment by jxnblk** [comment]
Thanks to @SaraVieira this now works!! :tada: https://mobile.twitter.com/NikkitaFTW/status/1113054141377662976

**Comment by mspronk** [comment]
In case someone runs into the related problem of random websocket ports being assigned, and using a container such as Docker which only forwards explicit ports; the workaround (or hack) I ended up applying was:

Because mdx-deck uses random websocket ports, and we can not expose them on Docker, we need to override
`mdx-deck/lib/dev.js` , around line 18, with explicit hot ports (could be 1 port as well, but using 3 reduces the chance it accidentally is being used already):
```
  opts.hotPort = await getPort({port: [31230, 31231, 31232]})
```
and then forward them, along with your actual gatsby port - 8000 in this case - in `docker run`:
```
... -p 8000:8000 -p 31230:31230 -p 31231:31231 -p 31232:31232
```

We also need to update the default hostname to work with Docker:
in `mdx-deck/cli.js`, around line 91, set
```
  host: '0.0.0.0',
```
