### ISSUE TITLE
My content is not slidered

### ISSUE THREAD

**Issue by ozfm** [jxnblk/mdx-deck#19]
Hi,

I separated my content by "---" markdown but i have only 1 slide ( slide.png ) 
![image](https://user-images.githubusercontent.com/16835445/43463517-0855f928-94d9-11e8-9d9e-9a88f2145c5d.png)

**Comment by jxnblk** [comment]
Thanks for reporting this! Would you mind sharing the MDX code in a snippet?

**Comment by felizalde** [comment]
I had the same problem. @ozfm, are you using it on Windows? 

Apparently the regex `/\n---\n/` 'not works' in Windows. Because the end-of-line char should be '\r\n' . If you change this [line](https://github.com/jxnblk/mdx-deck/blob/fcd9232ed0111d9363f6610c51680995ec325f32/lib/loader.js#L7) with the regex `/\r\n---\r\n/` should works fine.

I've test manually the issue with tables, and this approach work fine too.
