### ISSUE TITLE
Styling inside components

### ISSUE THREAD

**Issue by JJ** [jxnblk/mdx-deck#221]
I have used the background image like this:
```
---
<Image src='https://farm5.staticflickr.com/4810/31993107578_77df74653c_k_d.jpg' alt='comenzando' />

# That's me!
```
After importing the component. The image is OK, but I can't seem to get the text right on the page, either it's on top or on the bottom. Can it be shown centered?

**Comment by jxnblk** [comment]
Sorry, not sure I understand the question. You mention a background image, but the code shows the `img` tag...

**Comment by JJ** [comment]
Ah, it was Image. Sorry, stupid me.

**Comment by JJ** [comment]
I've updated it (and reopen, if you don't mind)

**Comment by jxnblk** [comment]
For the Image component, you’ll need to pass the content as children iirc

**Comment by JJ** [comment]
Thanks. It is now in the image, but the style is not the same as the rest
of the deck. I'm using h1, it gets the font right, but not the size; it's
also on the top of the page. Does it have different styling then?

**Comment by JJ** [comment]
Besides, I cant style the content using the `style` attribute. Is there something I'm missing here?

**Comment by JJ** [comment]
In general, how can you change styling inside a component? For instance, I would like to make the font in the full-screen code bigger. Is that possible?

**Comment by tomwayson** [comment]
>  It is now in the image, but the style is not the same as the rest of the deck. I'm using h1, it gets the font right, but not the size; it's also on the top of the page.

I'm having almost exactly the same issue. 

For example, w/ the dark theme (so that the text will be visible over the image) and this code:

```mdx
import { Image } from 'mdx-deck'

<Image src="https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=2048&q=20">

# Slide title
Some text
</Image>
```

I get this: 

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/662944/50866188-d3ee3200-135d-11e9-9919-06827e2c98c2.png">

Note how the slide content is not centered vertically and that there is a `1em` margin above the image.

Where as with:

```mdx
# Slide title
Some text
```

I get: 

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/662944/50866264-1f084500-135e-11e9-9a9c-87dd624d1c58.png">

How can I set the background image for a slide and have the text content be vertically centered the way it would otherwise. Should I be using a custom layout instead?

**Comment by slushman** [comment]
You could apply styling to the Image component. Something like:

`<Image 
  src="https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=2048&q=20"
  style={{
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  }}
>`

That seems to work for me. Not sure why that wouldn't be the default styling for this use case though.

**Comment by jxnblk** [comment]
The Image component intentionally doesn't use the same styles as the default slide layout – if you want to center items, use the method described by @slushman
