### ISSUE TITLE
Optimize bundle size

### ISSUE THREAD

**Issue by pengx17** [jxnblk/mdx-deck#294]
The bundle size looks like too much assets has been builded with. After output the bundle performance via webpack bundle analyzer, it shows that a lot of non-required syntax highlighter related stuff in included. 

Please see the screenshot:

![image](https://user-images.githubusercontent.com/584378/54966526-79a15c80-4faf-11e9-8fc1-9910499e7f0e.png)

Both of the biggest two rectangles (highlight.js and refractor) are either required by hljs and prism. All languages are loaded in the assets. 

some proposed suggestions:
- use LightAsync build of https://github.com/conorhastings/react-syntax-highlighter
- let the user to load the required language/style assets
- add a webpack loader to transform `<code>` blocks at build time

**Comment by jxnblk** [comment]
The changes in #328 should help reduce the bundle size. Closing this out for now since the changes planned for v3 will handle this a little differently

**Comment by rohit-gohri** [comment]
This is still a problem. My bundle has almost 1MB extra because of highlight.js and refractor even though I'm not using the syntax highlighter theme.

There are 2 problems I could think of:
1. All the languages from react-syntax-highlighter are imported.
The recommended way to import them is something like:
```js
import Prism from 'react-syntax-highlighter/dist/esm/prism-light'
import javascript from 'react-syntax-highlighter/dist/esm/languages/prism/javascript'
import typescript from 'react-syntax-highlighter/dist/esm/languages/prism/typescript'

Prism.registerLanguage('javascript', javascript)
Prism.registerLanguage('typescript', typescript)

```
We could add js/ts support and add instructions on how to add others themselves.

2. The other major problem is lines like these:

https://github.com/jxnblk/mdx-deck/blob/88402f5f1e01d8f62359a3af1e527c1fc143d0bc/packages/mdx-deck/index.js#L1

This makes webpack evaluate and bundle all themes even if we are using one.

We could add `"sideEffects": false` in the themes package to tell webpack to remove the themes that are unused(react-syntax-highlighter also has it https://github.com/conorhastings/react-syntax-highlighter/pull/152).
Docs: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free


Difference this could make:
Before: Around 2.05MB
![image](https://user-images.githubusercontent.com/31949290/77338306-2f80c180-6d50-11ea-965c-f94a5ddbd309.png)

After: Around 1.04MB
Just added `"sideEffects": false` to `@mdx-deck/themes`'s package.json in node_modules.
![image](https://user-images.githubusercontent.com/31949290/77340783-ce5aed00-6d53-11ea-9969-a23400eef4e7.png)

If the suggestions seem alright then I could open a PR.
