### ISSUE TITLE
How to resize / reorganise sections in presenter mode?

### ISSUE THREAD

**Issue by AniaMakes** [jxnblk/mdx-deck#307]
Hello! I was hoping for some guidance where to edit to get sections of the presenter mode to be different size - I am struggling to read the notes in their current location and would love them to be able to swap the `notes` with the `current slide`. 

Many thanks!

**Comment by Taar** [comment]
I don't think there is a way to reconfigure the `Presenter` component without modifying the source code. Have a look at [`Presenter line 56`](https://github.com/jxnblk/mdx-deck/blob/master/packages/components/src/Presenter.js#L56).

I think there is another way, thought it might not work as I haven't tried it. Since the notes are registered with the slide's index, you could create a `Provider` component which would place the current slide's note into a floating element somewhere else on the screen. The `Provider` gets passed props with all the information you would need. I created a pr #296 that updates the docs with an example on how to create a `Provider`. You would just need to hide the floating element in every other mode save for the `presenter` mode. I hope this helps.

**Comment by AniaMakes** [comment]
Great, thanks, that's enough information to get me started :smiley:

**Comment by jxnblk** [comment]
For the current API what @Taar suggested is probably the best route, but I'm looking into making things like this more customizable in a future version. Going to close this out for now, but feel free to open a new issue if you have any other questions/issues
