### ISSUE TITLE
Feature request: preserve slide element & state between different pages

### ISSUE THREAD

**Issue by pengx17** [jxnblk/mdx-deck#380]
It looks like in the latest version, only the current page will be rendered and the inactive ones  will be destructed. However a common issue that we do want the inactive pages are still cached in memory so when we switch pages back and forth, the page will get back without flicking especially if the page has some external resources (like an iframe), or preserve the state if there we a text input.

It seems this was not an issue in v1, but in version 2 mdx-deck adopted Reach Router which will handle page's lifecycle.

**Comment by jxnblk** [comment]
To preserve state, you can use a [custom Provider component](https://github.com/jxnblk/mdx-deck/blob/master/docs/advanced.md#custom-provider-component). As for the other loading issues, this likely won't change since loading a large deck (e.g. with 100s of slides) would encounter different issues – you can probably leverage `useSteps` or the `Appear` component for custom use-cases

**Comment by pengx17** [comment]
Not sure with the provider itself if we could control the lifespan of a slide. What I want to achieve is not pre-render all slides during the initial loading, but to lazily render the slides once navigated and cache them in the memory to quickly recover from previous state.

**Comment by jxnblk** [comment]
Some of the upcoming integrations with Gatsby should help cover lazy rendering. For images specifically, those will need more work, but if you're interested in trying the bleeding edge version, see #390

**Comment by pengx17** [comment]
Looks like it will be a huge rewrite and very interesting. I will halt here for sometime until the next time I write a slideshow. Your work is admirable btw!

**Comment by jxnblk** [comment]
Thanks! Going to close this out for now, since I'm unsure of what the specific change needed for this request should be. Generally speaking, the upcoming changes in v3 should help with performance generally, and I'll try to look into what's possible with regard to prefetching things like image requests
